def build_env(apis: list[str], api_keys: dict[str, str], database: str) -> str:
    API_KEY_MAP = {
        "openrouter": ("OPENROUTER_API_KEY", "OpenRouter API key for LLM routing"),
        "tavily": ("TAVILY_API_KEY", "Tavily search API key"),
    }

    DB_MAP = {
        "postgres": [
            ("DATABASE_URL", "postgres://user:pass@localhost:5432/dbname", "PostgreSQL connection string [REQUIRED]"),
        ],
        "firebase": [
            ("FIREBASE_PROJECT_ID", "", "Firebase project ID [REQUIRED]"),
            ("FIREBASE_API_KEY", "", "Firebase web API key [REQUIRED]"),
            ("FIREBASE_AUTH_DOMAIN", "", "Firebase auth domain [OPTIONAL]"),
        ],
    }

    lines = [
        "# .env — Generated by CodeGarden",
        "# REQUIRED keys must be set before running. OPTIONAL keys can be left empty.",
        "",
        "# CodeGarden backend [REQUIRED]",
        "OPENAI_API_KEY=your-openai-key-here",
        "",
    ]

    if apis:
        lines.append("# External APIs")
        for api in apis:
            if api in API_KEY_MAP:
                key_name, comment = API_KEY_MAP[api]
                value = api_keys.get(api, f"your-{api}-key-here")
                lines.append(f"# {comment} [REQUIRED]")
                lines.append(f"{key_name}={value}")
                lines.append("")

    if database in DB_MAP:
        lines.append("# Database")
        for key_name, default, comment in DB_MAP[database]:
            value = default if default else f"your-{key_name.lower()}-here"
            lines.append(f"# {comment}")
            lines.append(f"{key_name}={value}")
            lines.append("")

    return "\n".join(lines)
